config/routes.rb
Rails.application.routes.draw do
  devise_for :login, path: 'auth', path_names: { 
    sign_up: 'sign-up',
    sign_in: 'sign-in', 
    sign_out: 'sign-out' 
  }

  authenticated :login do
    root 'pages#dashboard', as: :login_root
  end

  root 'pages#home'

  # Requires authentication, redirects
  resources :caregivers
  resources :clients
end

app/models/concerns/taggable.rb
# This concern adds functionality for having tags.
module Taggable
  extend ActiveSupport::Concern

  included do
    # destroy only joins, not tag
    has_many :tag_joins, as: :taggable, inverse_of: :taggable,
                         dependent: :destroy
    has_many :tags, through: :tag_joins, inverse_of: model_name.plural.to_sym
  end
end

app/views/shared/forms/_basic_info.html.haml
.card
  %h2 Basic Info
  %hr
  .form-group
    = form.label :first_name
    = form.text_field :first_name, class: 'form-control'
  .form-group
    = form.label :first_name
    = form.text_field :last_name, class: 'form-control'
  .form-group
    = form.label :gender
    - options = form.object.class.genders.map { |k, _| [k.titleize, k] }
    = form.select :gender, options, { prompt: true }, 
      { class: 'form-control' }
  .form-group
    = form.label :birthdate
    = form.date_select :birthdate, 
      { order: [:month, :day, :year], start_year: Time.now.year - 100, end_year: Time.now.year - 18, prompt: true }, 
      { class: 'form-control' }
  .form-group
    = form.label :phone_number
    = form.phone_field :phone_number, class: 'form-control', placeholder: '(###) ###-####'
  .form-group
    = form.label :address
    = form.text_field :street_address, class: 'form-control', placeholder: 'Street address'
    = form.text_field :extra_address, class: 'form-control', placeholder: 'Suite number'
    = form.text_field :city, class: 'form-control', placeholder: 'City'
    = form.select :state, Locatable::STATES.invert, { prompt: 'State' }, { class: 'form-control' }
    = form.text_field :zip_code, class: 'form-control', placeholder: 'ZIP Code'
  - if form.object.respond_to? :description
    .form-group
      = form.label :description
      = form.text_area :description, class: 'form-control', placeholder: 'Please input additional information'

app/views/shared/forms/_tags.html.haml
.card
  %h2 Tags
  %hr
  - { health: ['Health', @health_tags], environment: ['Environment', @environment_tags], task: ['Needs', @task_tags] }.each do |type, combo|
    - name, tags = combo
    %h3= name.to_s.titleize
    .well
      = form.collection_check_boxes :tag_ids, tags, :id, :name do |b|
        = b.label class: "tag tag-#{type}" do
          = b.check_box
          = b.text