config/routes.rb
Rails.application.routes.draw do
  devise_for :login, path: 'auth', path_names: { 
    sign_up: 'sign-up',
    sign_in: 'sign-in', 
    sign_out: 'sign-out' 
  }

  authenticated :login do
    root 'pages#dashboard', as: :login_root
  end

  root 'pages#home'

  # Requires authentication, redirects
  resources :caregivers
  resources :clients
end

app/models/caregiver.rb
# This class represents a caregiver as part of an organization.
class Caregiver < ApplicationRecord
  include Birthdatable, Emailable, Genderable, Organizable, Locatable,
          Loginable, Nameable, Phonable, Taggable
  # Messageable
end

app/controllers/caregivers_controller.rb
# This controller handles all requests for caregiver resources.
class CaregiversController < ApplicationController
  load_and_authorize_resource

  before_action :setup
  before_action :setup_tags, only: [:new, :create, :edit, :update]
  before_action :setup_breadcrumbs

  def index
    @caregivers = current_user.caregivers
  end

  def new
    @caregiver = Caregiver.new
  end

  def create
  end

  def show
    @tags = @caregiver.tags.order(:name)
  end

  def edit
  end

  def update
    if @caregiver.update(caregiver_params)
      flash[:success] = "Successfully updated #{@caregiver.name}'s profile."
      redirect_to @caregiver
    else
      render :edit
    end
  end

  def destroy
    @caregiver.destroy
    flash[:success] = "Successfully deleted #{@caregiver.name}'s profile"
    redirect_to caregivers_path
  end

  private

  def setup
    return if params[:id].blank?
    @caregiver = Caregiver.find(params[:id])
  end

  def setup_tags
    @health_tags = Tag.health.sort_by(&:name)
    @environment_tags = Tag.environment.sort_by(&:name)
    @task_tags = Tag.task.sort_by(&:name)
  end

  def setup_breadcrumbs
    index = [['Caregivers', caregivers_path]]
    @breadcrumbs = case action_name
                   when /index/ then index
                   when /new|create/ then index << ['New', new_caregiver_path]
                   when /show/ then index << [@caregiver.name, @caregiver]
                   when /edit|update/
                     index << [@caregiver.name, @caregiver] <<
                     ['Edit', edit_caregiver_path(@caregiver)]
                   end
  end

  def caregiver_params
    params.require(:caregiver)
          .permit(:first_name, :last_name, :gender, :birthdate, :phone_number,
                  :street_address, :extra_address, :city, :state, :zip_code,
                  tag_ids: [])
  end
end

app/views/caregivers/_form.html.haml
= form_for @caregiver do |caregiver_form|
  = render partial: 'shared/form_errors', locals: { form: caregiver_form }
  = render partial: 'shared/forms/basic_info', locals: { form: caregiver_form }
  = render partial: 'shared/forms/tags', locals: { form: caregiver_form }    
  = caregiver_form.submit "#{@caregiver.new_record? ? 'Add' : 'Update'} caregiver", class: 'btn btn-primary btn-lg'

app/views/caregivers/edit.html.haml
.container
  %h1.text-center Edit #{@caregiver.name}
  .row
    .col-md-8.col-md-offset-2
      = render partial: 'caregivers/form'

app/views/caregivers/index.html.haml
.container
  %h1.text-center Caregivers
  - if @caregivers.any?
    %table.table.table-striped
      %thead
        %th First name
        %th Last name
        %th Phone number
        %th City
        %th Upcoming visits
      %tbody
        - @caregivers.each do |cg|
          %tr
            %td= link_to cg.first_name, cg
            %td= link_to cg.last_name, cg
            %td= link_to cg.phone_number_formatted, "tel:#{cg.phone_number}"
            %td= cg.city
            %td
  %hr
  = link_to 'Add Client', new_client_path, class: 'btn btn-success'

app/views/caregivers/new.html.haml
.container
  %h1.text-center Add Caregiver
  .row
    .col-md-8.col-md-offset-2
      = render partial: 'caregivers/form'

app/views/caregivers/show.html.haml
.container
  %h1.text-center= @caregiver.name
  .row
    .col-md-4
      .card
        %h2 Info
        %hr
        %ul
          - [:age, :gender, :street_address, :city, :state, :zip_code].each do |field|
            %li
              %strong= "#{field.to_s.titleize}:"
              = @caregiver.send(field)
    .col-md-4
      = render partial: 'shared/tags'
    .col-md-4
      .card
        %h2 Upcoming Visits
        %hr
  %hr
  = link_to 'Edit caregiver', edit_caregiver_path(@caregiver), 
                              class: 'btn btn-primary'
  = link_to 'Delete caregiver', @caregiver, method: :delete,
                                            class: 'btn btn-danger',
                                            data: { confirm: 'Are you sure?' }