config/routes.rb
Rails.application.routes.draw do
  devise_for :login, path: 'auth', path_names: { 
    sign_up: 'sign-up',
    sign_in: 'sign-in', 
    sign_out: 'sign-out' 
  }

  authenticated :login do
    root 'pages#dashboard', as: :login_root
  end

  root 'pages#home'

  # Requires authentication, redirects
  resources :caregivers
  resources :clients
end

app/views/pages/caregiver_dashboard.html.haml
.container
  %h1.text-center Dashboard
  %ul
  

app/views/pages/dashboard.html.haml
.container
  %h1.text-center #{@group.name}
  .row
    .col-md-3
      = quick_look(@clients.length, 'Clients', clients_path, 'home', 'success')
    .col-md-3
      = quick_look(@caregivers.length, 'Caregivers', caregivers_path, 'user', 'info')
    .col-md-3
      = quick_look(8, 'Scheduled Visits', '/', 'calendar', 'warning')
    .col-md-3
      = quick_look(4, 'Late Visits', '/', 'alarm-clock', 'danger')
  .card
    %h2 This is
    %hr
    %p just a card

app/views/pages/home.html.haml
.container
  %h1.text-center Home

app/views/pages/manager_dashboard.html.haml
.container
  %h1.text-center #{@organization.name}
  .row
    .col-md-3
      = quick_look(@clients.length, 'Active Clients', clients_path, 'success')
    .col-md-3
      = quick_look(@caregivers.length, 'Active Caregivers', caregivers_path, 'info')
    .col-md-3
      = quick_look(18, 'Upcoming Discharges', '/', 'warning')
    .col-md-3
      = quick_look(20, 'Unfilled Visits', '/', 'danger')
  .row
    .col-md-6
      .card
        %h2 Top 10 Client Tags
        %hr
        = pie_chart @client_tags
    .col-md-6
      .card
        %h2 Top 10 Caregiver Tags
        %hr
        = pie_chart @caregiver_tags
  .row
    .col-md-3
      = quick_look(number_with_delimiter(2743), 'Hours Billed', '/', 'success')
    .col-md-3
      = quick_look('$28,800', 'Avg. Monthly Revenue', caregivers_path, 'info')
    .col-md-3
      = quick_look('$14,400', 'Avg. Increase', '/', 'warning')
    .col-md-3
      = quick_look("10.22%", 'Readmission Rate', '/', 'danger')
  .row
    .col-md-5
      .card
        %h2 Revenue Split
        %hr
        = pie_chart @revenue_split
    .col-md-7
      .card
        %h2 Client Count
        %hr
        = column_chart @client_count
  .row
    .col-md-3
      = quick_look(18, 'Upcoming Visits', '/', 'success')
    .col-md-3
      = quick_look(14, 'Ongoing Visits', '/', 'info')
    .col-md-3
      = quick_look(4, 'Concluded Visits', '/', 'warning')
    .col-md-3
      = quick_look(2, 'Late Visits', '/', 'danger')
  = render partial: 'shared/calendar'